name: driverfcst
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - plotly
  - pycaret
  - pmdarima
  - prophet  # No version means "latest available"
  - requests